## 【課題1】内積を手計算しよう

内積A・B = 4+3-10-48+14+72+9 = 44

積は  
[6, 29, -20]  
[12, 52, 38]  
[-18, -51, -48]

## 【課題2】1次元配列の内積をfor文で計算しよう
## 【課題3】多次元配列の内積をfor文で計算しよう
## 【課題4】内積をnp.dotで計算しよう


In [20]:
import numpy as np

A = np.array([[-1, 2, 3],
              [4, -5, 6],
              [7, 8, -9]])

B = np.array([[0, 2, 1],
              [0, 2, -8],
              [2, 9, -1]])

C = np.empty((A.shape[1],B.shape[0]))

for i in range(A.shape[1]):
    for j in range(B.shape[0]):
        a = 0
        for k in range(3):
            a += A[i][k] * B[k][j]
        C[i][j] = a

In [21]:
C

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

In [22]:
np.dot(A,B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【課題5】内積ができないときはどうするか

In [23]:
import numpy as np

A = np.array([[-1, 2, 3],
              [4, -5, 6]])

B = np.array([[-9, 8, 7],
              [6, -5, 4]])

In [24]:
np.dot(A,B)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

エラーがでる理由は、行列Aの列数と行列Bの行数が合っていないから。転置行列に変換して求める。

In [26]:
np.dot(A,B.T)

array([[ 46,  -4],
       [-34,  73]])